#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: nginx
##  namespace: build
#  labels:
#    app: nginx
#spec:
#  selector:
#    matchLabels:
#      app: nginx
#  replicas: 6
#  strategy:
#    rollingUpdate:
#      maxSurge: 25%
#      maxUnavailable: 25%
#    type: RollingUpdate
#  template:
#    metadata:
#      labels:
#        app: nginx
#    spec:
#      containers:
#      - name: nginx
#        image:  nginx:latest
#        resources:
#          requests:
#            cpu: 100m
#            memory: 100Mi
#          limits:
#            cpu: 100m
#            memory: 100Mi
#        livenessProbe:
#          tcpSocket:
#            port: 80
#          initialDelaySeconds: 5
#          timeoutSeconds: 5
#          successThreshold: 1
#          failureThreshold: 3
#          periodSeconds: 10
#        env:
#        - name: DB_HOST
#          value: POSTGRES
#        ports:
#        - containerPort:  80
#          name: nginx