kind: Pod
apiVersion: v1
metadata:
  name: foo-app-v2
  labels:
    app: foo-v2
    svc: foo-bar-v2
spec:
  containers:
    - name: foo-app-v2
      image: nginx:1.22.0
      volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: foo-config-v2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo-config-v2
data:
  index.html: |
    foo
---
kind: Service
apiVersion: v1
metadata:
  name: foo-service-v2
spec:
  selector:
    app: foo-v2
  ports:
    - port: 80